services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-owlculus}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-owlculus_secure_password}
      POSTGRES_DB: ${POSTGRES_DB:-owlculus}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-owlculus} -d ${POSTGRES_DB:-owlculus}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - owlculus-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-owlculus}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-owlculus_secure_password}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-owlculus}
      SECRET_KEY: ${SECRET_KEY:-development_key_not_secure}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost}
      BACKEND_URL: ${BACKEND_URL:-http://localhost:8000}
    volumes:
      - uploads_data:/app/uploads
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - owlculus-network

  # Database Initialization
  db-init:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-owlculus}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-owlculus_secure_password}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-owlculus}
      SECRET_KEY: ${SECRET_KEY:-development_key_not_secure}
      ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin123}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@owlculus.local}
    command: python3 /app/init_db_auto.py
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./scripts/init_db_auto.py:/app/init_db_auto.py
    networks:
      - owlculus-network
    restart: "no"

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - owlculus-network

volumes:
  postgres_data:
    driver: local
  uploads_data:
    driver: local

networks:
  owlculus-network:
    driver: bridge