"""Production and in-memory adapters for one plugin run."""

from collections.abc import Callable, Iterator, Mapping
from contextlib import AbstractContextManager, contextmanager
from dataclasses import dataclass
from tempfile import SpooledTemporaryFile
from typing import Any, BinaryIO, Protocol, cast

from fastapi import UploadFile
from sqlmodel import Session, select
from starlette.datastructures import Headers

from app.database import models
from app.schemas import evidence_schema as schemas
from app.schemas.entity_schema import EntityCreate, EntityUpdate, IpAddressData
from app.schemas.evidence_schema import FolderCreate
from app.services.api_key_vault import ApiKeyVault, Provider, StaticApiKeyVault
from app.services.entity_service import EntityService
from app.services.evidence_service import EvidenceService

from .plugin_types import (
    DomainSubdomainsWrite,
    EntityWrite,
    EvidenceWrite,
    IpAddressWrite,
    ResultEvent,
)


class EvidenceSink(Protocol):
    async def write(self, request: EvidenceWrite, user: models.User) -> None: ...


class EntitySink(Protocol):
    async def write(
        self, request: EntityWrite, case_id: int, user: models.User
    ) -> None: ...


class ListEvidenceSink:
    def __init__(self, writes: list[EvidenceWrite]):
        self._writes = writes

    async def write(self, request: EvidenceWrite, user: models.User) -> None:
        self._writes.append(request)


class ListEntitySink:
    def __init__(self, writes: list[EntityWrite]):
        self._writes = writes

    async def write(
        self, request: EntityWrite, case_id: int, user: models.User
    ) -> None:
        self._writes.append(request)


class ServiceEvidenceSink:
    def __init__(self, session: Session, artifact_id: str | None = None):
        self._session = session
        self.artifact_id = artifact_id

    async def write(self, request: EvidenceWrite, user: models.User) -> None:
        service = EvidenceService(self._session)
        folder = self._session.exec(
            select(models.Evidence).where(
                models.Evidence.case_id == request.case_id,
                models.Evidence.is_folder == True,
                models.Evidence.title == "Plugin Results",
            )
        ).first()
        if folder is None:
            folder = await service.create_folder(
                FolderCreate(
                    case_id=request.case_id,
                    title="Plugin Results",
                    description="Auto-created folder for all plugin and hunt results",
                    folder_path=None,
                    parent_folder_id=None,
                ),
                current_user=user,
            )
        with SpooledTemporaryFile() as temporary_file:
            temporary_file.write(request.content.encode())
            temporary_file.seek(0)
            await service.create_evidence(
                evidence=schemas.EvidenceCreate(
                    case_id=request.case_id,
                    title=f"{request.display_name} results.txt",
                    description=f"Output generated by {request.display_name} plugin",
                    evidence_type="file",
                    category=request.category,
                    folder_path=folder.folder_path,
                    parent_folder_id=folder.id,
                ),
                current_user=user,
                artifact_id=self.artifact_id,
                file=UploadFile(
                    filename=request.filename,
                    file=cast(BinaryIO, temporary_file),
                    headers=Headers({"content-type": "text/plain"}),
                ),
            )


class ServiceEntitySink:
    def __init__(self, session: Session):
        self._service = EntityService(session)

    async def write(
        self, request: EntityWrite, case_id: int, user: models.User
    ) -> None:
        if isinstance(request, IpAddressWrite):
            await self._write_ip(request, case_id, user)
        else:
            await self._write_domain(request, case_id, user)

    async def _write_ip(
        self, request: IpAddressWrite, case_id: int, user: models.User
    ) -> None:
        existing = await self._service.find_entity_by_ip_address(
            case_id, request.address, current_user=user
        )
        if existing:
            await self._service.enrich_entity_description(
                case_id,
                cast(int, existing.id),
                request.description,
                current_user=user,
            )
            return
        data: dict[str, Any] = {
            "ip_address": request.address,
            "description": request.description,
        }
        if request.sources:
            data["sources"] = dict(request.sources)
        await self._service.create_entity(
            case_id,
            EntityCreate(
                entity_type="ip_address", data=IpAddressData(**data).model_dump()
            ),
            current_user=user,
        )

    async def _write_domain(
        self, request: DomainSubdomainsWrite, case_id: int, user: models.User
    ) -> None:
        existing = await self._service.find_entity_by_domain(
            case_id, request.domain, current_user=user
        )
        if existing:
            current_data = existing.data.copy()
            merged = {
                item["subdomain"]: item for item in current_data.get("subdomains", [])
            }
            for item in request.subdomains:
                previous = merged.get(item["subdomain"])
                if previous is None or (
                    item["resolved"] and not previous.get("resolved")
                ):
                    merged[item["subdomain"]] = item
            current_data["subdomains"] = sorted(
                merged.values(), key=lambda item: item["subdomain"]
            )
            await self._service.update_entity(
                case_id,
                cast(int, existing.id),
                EntityUpdate.model_validate({"data": current_data}),
                current_user=user,
            )
            return
        await self._service.create_entity(
            case_id,
            EntityCreate(
                entity_type="domain",
                data={
                    "domain": request.domain,
                    "description": (
                        f"Parent domain with {len(request.subdomains)} discovered subdomains"
                    ),
                    "subdomains": sorted(
                        request.subdomains, key=lambda item: item["subdomain"]
                    ),
                },
            ),
            current_user=user,
        )


@dataclass(frozen=True)
class PluginRun:
    session: Session
    user: models.User
    case_id: int | None
    save_to_case: bool
    api_keys: ApiKeyVault
    evidence: EvidenceSink
    entities: EntitySink
    execution_control_id: int | None = None
    operation_id: str = "plugin"

    @classmethod
    def for_test(
        cls,
        *,
        session: Session,
        user: models.User,
        api_keys: Mapping[Provider, str | None],
        evidence: list[EvidenceWrite],
        entities: list[EntityWrite],
        case_id: int | None = None,
        save_to_case: bool = False,
    ) -> "PluginRun":
        return cls(
            session,
            user,
            case_id,
            save_to_case,
            StaticApiKeyVault(api_keys),
            ListEvidenceSink(evidence),
            ListEntitySink(entities),
        )

    def key(self, provider: Provider) -> str | None:
        return self.api_keys.get_key(provider)

    def missing_key(self, provider: Provider) -> ResultEvent:
        label = provider.value.replace("_", " ").title()
        return ResultEvent.error(
            f"API key required for {label}. Add it in Admin → Configuration → API Keys."
        )


class ProductionPluginRunAdapter:
    """Own a production session for exactly as long as a run context is used."""

    def __init__(
        self,
        session_factory: Callable[[], AbstractContextManager[Session]],
        api_key_vault_factory: Callable[[Session], ApiKeyVault],
    ):
        self._session_factory = session_factory
        self._api_key_vault_factory = api_key_vault_factory

    @contextmanager
    def open(
        self,
        *,
        user: models.User,
        case_id: int | None,
        save_to_case: bool,
        operation_id: str = "plugin",
    ) -> Iterator[PluginRun]:
        with self._session_factory() as session:
            yield PluginRun(
                session,
                user,
                case_id,
                save_to_case,
                self._api_key_vault_factory(session),
                ServiceEvidenceSink(session),
                ServiceEntitySink(session),
                operation_id=operation_id,
            )
